version: "3.3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data/databaseinit.sql:/docker-entrypoint-initdb.d/databaseinit.sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=tendersadmin
      - MYSQL_ROOT_PASSWORD=i@hrX!48Ya6C9Zx%BpVRYBG&Q
      - MYSQL_DATABASE=tenders
      - MYSQL_PASSWORD=i@hrX!48Ya6C9Zx%BpVRYBG&Q
